/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Producto;
import Models.ProductoDAO;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.FILES_AND_DIRECTORIES;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author alons
 */
public class ProductoForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductoForm
     */
    ProductoDAO pDAO = new ProductoDAO();
    Producto prod = new Producto();
    DefaultTableModel modelo = new DefaultTableModel();
    int id;

    public ProductoForm() {
        initComponents();
        listar();
    }

    void listar() {
        List<Producto> lista = pDAO.listart();
        modelo = (DefaultTableModel) tablaProd.getModel();
        Object[] ob = new Object[10];

        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getId_producto();
            ob[1] = lista.get(i).getId_categoria();
            ob[2] = lista.get(i).getNombre_Producto();
            ob[3] = lista.get(i).getDescripcion_Producto();
            ob[4] = lista.get(i).getMarca();
            ob[5] = lista.get(i).getStock();
            ob[6] = lista.get(i).getPrecio();
            ob[7] = lista.get(i).getImagen_Producto();
            ob[8] = lista.get(i).getCreado();
            ob[9] = lista.get(i).getActualizado();

            modelo.addRow(ob);
        }
        tablaProd.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtImg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbImagen = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Gestion de productos");
        setPreferredSize(new java.awt.Dimension(1300, 900));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel1.setText("Nombre Producto:");

        txtProducto.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel2.setText("Descripción Producto:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel3.setText("Marca:");

        txtMarca.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel4.setText("Stock:");

        txtStock.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel5.setText("Imagen:");

        txtImg.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jButton1.setText("Examinar...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel6.setText("Precio:");

        txtPrecio.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logoazul.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        jLabel8.setText("Gestiona Productos");

        btnActualizar.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel9.setText("Imagen del producto");

        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel10.setText("Categoria:");

        txtCategoria.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel11.setText("Código Producto:");

        txtCodigo.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(405, 405, 405)
                                        .addComponent(jLabel9))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)))
                        .addGap(0, 398, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProducto)
                                .addComponent(txtMarca)
                                .addComponent(txtStock)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addComponent(txtCategoria))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        tablaProd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaProd.setFont(new java.awt.Font("Open Sans", 0, 20)); // NOI18N
        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Producto", "Categoria", "Nombre", "Descripción", "Marca", "Stock", "Precio", "Nombre Imagen", "Creado"
            }
        ));
        tablaProd.setRowHeight(30);
        tablaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String nombre_imagen;
        String root = "C:\\wamp64\\www\\Servinox\\uploads\\";
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("C:\\wamp64\\www\\Servinox\\uploads\\"));
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter FiltroJPG = new FileNameExtensionFilter("*.JPG", "jpg");
        FileNameExtensionFilter FiltroJPEG = new FileNameExtensionFilter("*.JPEG", "jpeg");
        FileNameExtensionFilter FiltroPNG = new FileNameExtensionFilter("*.PNG", "png");
        fc.setFileFilter(FiltroPNG);

        fc.setFileFilter(FiltroJPEG);
        fc.setFileFilter(FiltroJPG);

        int selec = fc.showOpenDialog(this);
        if (selec == JFileChooser.APPROVE_OPTION) {
            File img = fc.getSelectedFile();

            nombre_imagen = img.getName();
            boolean save = img.renameTo(new File("C:\\wamp64\\www\\Servinox\\uploads\\" + img.getName()));
            if (save) {
                System.out.println("Imagen movida");
            } else {
                System.out.println("Imagen no movida");
            }
            txtImg.setText(nombre_imagen);

            int x = lbImagen.getWidth();
            int y = lbImagen.getHeight();
            String put = root + nombre_imagen;
            Imagen imagen = new Imagen(x, y, put);
            lbImagen.removeAll();
            lbImagen.repaint();
            lbImagen.add(imagen);
            lbImagen.repaint();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
        limpiarTabla();
        listar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizar();
        limpiarTabla();
        listar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProdMouseClicked
        int fila = tablaProd.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una fila");
        } else {
            id = Integer.parseInt(tablaProd.getValueAt(fila, 0).toString());
            int id_categoria = Integer.parseInt(tablaProd.getValueAt(fila, 1).toString());
            String nom = tablaProd.getValueAt(fila, 2).toString();
            String desc = tablaProd.getValueAt(fila, 3).toString();
            String marca = tablaProd.getValueAt(fila, 4).toString();
            int stock = Integer.parseInt(tablaProd.getValueAt(fila, 5).toString());
            String precio = tablaProd.getValueAt(fila, 6).toString();
            String img = tablaProd.getValueAt(fila, 7).toString();

            txtCodigo.setText(String.valueOf(id));
            txtCategoria.setText(String.valueOf(id_categoria));
            txtProducto.setText(nom);
            txtDescripcion.setText(desc);
            txtMarca.setText(marca);
            txtStock.setValue(tablaProd.getValueAt(fila, 5));
            txtImg.setText(img);
            txtPrecio.setText(precio);

            //SETEAR IMAGEN
            String root = "C:\\wamp64\\www\\Servinox\\uploads\\";
            String put = root + img;
            System.out.println(put);
            int x = lbImagen.getWidth();
            int y = lbImagen.getHeight();
            Imagen imagen = new Imagen(x, y, put);
            lbImagen.removeAll();
            lbImagen.repaint();
            lbImagen.add(imagen);
            lbImagen.repaint();
        }
    }//GEN-LAST:event_tablaProdMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
        limpiarTabla();
        listar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    void agregar() {

        Producto p = new Producto();
        int cat = Integer.parseInt(txtCategoria.getText());
        ProductoDAO pDAO = new ProductoDAO();
        String nom = txtProducto.getText();
        String desc = txtDescripcion.getText();
        String marca = txtMarca.getText();
        int stock = Integer.parseInt(txtStock.getValue().toString());
        String img = txtImg.getText();

        Object[] ob = new Object[7];

        if (nom != null && desc != null && marca != null && stock != 0 && img != null && stock > 0) {
            double precio = Double.parseDouble(txtPrecio.getText());
            ob[0] = cat;
            ob[1] = nom;
            ob[2] = desc;
            ob[3] = marca;
            ob[4] = stock;
            ob[5] = precio;
            ob[6] = img;

            pDAO.add(ob);
            nuevo();
        } else {
            JOptionPane.showMessageDialog(this, "Es necesario rellenar todos los campos");
        }

    }

    void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    void actualizar() {
        int fila = tablaProd.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro");
        } else {
            int id_producto = Integer.parseInt(txtCodigo.getText());
            int id_categoria = Integer.parseInt(txtCategoria.getText());
            String nom = txtProducto.getText();
            String desc = txtDescripcion.getText();
            String marca = txtMarca.getText();
            int stock = Integer.parseInt(txtStock.getValue().toString());
            String img = txtImg.getText();
            Object[] ob = new Object[8];
            if (nom != null && desc != null && marca != null && stock != 0 && img != null) {
                double precio = Double.parseDouble(txtPrecio.getText());
                ob[0] = id_producto;
                ob[1] = id_categoria;
                ob[2] = nom;
                ob[3] = desc;
                ob[4] = marca;
                ob[5] = stock;
                ob[6] = precio;
                ob[7] = img;

                pDAO.actualizar(ob);
                JOptionPane.showMessageDialog(null, "Datos Actualizados");
                nuevo();
            };
        }
    }

    void eliminar() {
        int fila = tablaProd.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un registro");
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Desea ocultar este producto a las demas aplicaciones?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                pDAO.eliminar(id);

            }
            nuevo();
        }
    }

    void nuevo() {
        Object o = new Object();
        txtProducto.setText("");
        txtDescripcion.setText("");
        txtMarca.setText("");
        txtStock.setValue(new Integer(0));
        txtPrecio.setText("");
        txtImg.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtImg;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JSpinner txtStock;
    // End of variables declaration//GEN-END:variables
}
